version: 2
jobs:
  build:
    docker:
      #- image: "circleci/node:10.15.3-browsers-legacy@sha256:36b4b1f22459ae2174c9cf713f8e54e2a0df172bf27411859fd544f6f488833d"
      - image: node:8
    working_directory: ~/repo

    steps:
      - checkout
      #- run: sudo npm install lerna -g
      - run: lerna bootstrap
      - run: lerna run test

workflows:
  version: 2
  commit:
    jobs:
      - build
